version: '3.8'
services:
  web:
    image: odoo:19.0
    ports:
      - "8069:8069"
    environment:
      - HOST=${PGHOST}
      - PORT=${PGPORT}
      - USER=${PGUSER}
      - PASSWORD=${PGPASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]

volumes:
  odoo-web-data:
