version: '3.8'
services:
  web:
    build: .
    ports:
      - "8069:8069"
    environment:
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - ODOO_ADMIN_PASSWD
    volumes:
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-web-data:
