version: '3.1'

services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    environment:
      - HOST=${PGHOST}
      - PORT=${PGPORT}
      - USER=${PGUSER}
      - PASSWORD=${PGPASSWORD}
      - DBNAME=${PGDATABASE}
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons

volumes:
  odoo-data:
